### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by blockchainer2** [EthVM/evm-source-verification#52]
0xDb23400dB8A2b094cb5C9d65417362fd278866df  this contract developer didn't verify the contract source code, why this reposity has the contract source code?   the contract developer stole my USDT, could you help me?
how do you get the contract's source code???
this is what happened on me,  https://medium.com/@simith1122/hackers-stole-my-60-000-digital-currency-what-should-i-do-63da4fcf43c0

**Comment by olgakup** [comment]
Hi @[blockchainer2](https://github.com/blockchainer2), purpose of this repo is to verify that the source code of a contract is what's actually running on the Blockchain. As well as, get the contract info like abi, so that community members can see the sources code. As it was mentioned in the descriptionWe were able to

**Comment by Mehduzza420** [comment]
I need assistance with my account

**Comment by lucas7788** [comment]
> 0xDb23400dB8A2b094cb5C9d65417362fd278866df

this contract's developer didnt verify contract in ethscan, I  dont know  how you get the contract source code. @olgakup

**Comment by lucas7788** [comment]
> this contract's developer didnt verify contract in ethscan, I dont know how you get the contract source code. @olgakup

this contract's developer didnt verify contract in ethscan, I dont know how you get the contract source code. @olgakup

**Comment by Mehduzza420** [comment]
what should I do to track it. I have photos I can retrace the transactions

**Comment by lucas7788** [comment]
> what should I do to track it. I have photos I can retrace the transactions

what photos do you have??

**Comment by Mehduzza420** [comment]
Of the transactions  made. My account has been severely compromised. Been looking to get assistance and I was scammed from circle and paxful
